name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
jobs:
  build:
    name: Build
    runs-on: windows10-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ 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 }}
          SONAR_HOST_URL: ${{ http://localhost:9000/dashboard?id=NumerosPrimos }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ 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 }}
